### ISSUE TITLE
Export-XLSX with TimeSpan: Exception calling "AutoFitColumns" with "0" argument(s)

### ISSUE THREAD

**Issue by DarkLite1** [RamblingCookieMonster/PSExcel#11]
When using a TimeSpan in an object property the following error is produced:

    Exception calling "AutoFitColumns" with "0" argument(s): "Not a legal OleAut date."

Which originates from the function 'Export-XLSX' in almost the last line of the code:

    if($AutoFit)
    {
    $WorkSheet.Cells[$WorkSheet.Dimension.Address].AutoFitColumns()
    }

Reproducible as following:

    $DemoData = [PSCustomObject] @{
         Name = "Problem object"
         NoProblem = "6.04:53:33.2200000"
         Problem = [TimeSpan]::FromSeconds(53971559/100)
     }
     $File = "\\belcl001777\c$\users\gijbelsb\Downloads\Demo.xlsx"
     $DemoData | Export-XLSX -Path $File -WorksheetName 'Printers' -Table -AutoFit -Force

I don't know if this is a bug in the code, but when using 'Export-Csv' this isn't a problem.

**Comment by RamblingCookieMonster** [comment]
Ended up just converting any timespans to string, this will probably come up for other types as well

Cheers!

**Comment by DarkLite1** [comment]
Works perfectly! Thank you very much for fixing this :)
