### ISSUE TITLE
Get-Worksheet is not checking if a worksheet exists in the workbook

### ISSUE THREAD

**Issue by DarkLite1** [RamblingCookieMonster/PSExcel#12]
The following codes works fine and results in a ForestGreen header

    $DemoData = 1..10 | Foreach-Object{
        [PSCustomObject]@{
            Name       = "jsmith $_"
            EmployeeID = $EID
            Date       = $Date
        }
    }

    $File = "$env:TEMP\test.xlsx"
    $DemoData | Export-XLSX -Path $File -WorksheetName 'Printers' -Table -AutoFit -Force
    $Excel = New-Excel -Path $File
    $Worksheet = $Excel | Get-Worksheet -Name Printers
    
    $HeadParams = @{
        Header              = $True
        Bold                = $True
        Size                = '12'
        Color               = 'White'
        BackgroundColor     = 'ForestGreen' 
        HorizontalAlignment = 'Center'
        WrapText            = $True
    }
    $Worksheet | Format-Cell @HeadParams
    $Worksheet | Set-FreezePane -Row 2
    $Excel | Close-Excel -Save

However, when you change the input of Get-Worksheet to a non existing worksheet, no error is thrown and the formatting is not applied. It would be nice if it would throw an error when you specify a name for a worksheet and that worksheet name doesn't exist. So you know you made a mistake somewhere.

This code doesn't give a ForestGreen header and no error that the worksheet isn't found:

    $File = "$env:TEMP\test.xlsx"
    $DemoData | Export-XLSX -Path $File -WorksheetName 'Printers' -Table -AutoFit -Force
    $Excel = New-Excel -Path $File
    $Worksheet = $Excel | Get-Worksheet -Name UnexistingWorksheet
    
    $HeadParams = @{
        Header              = $True
        Bold                = $True
        Size                = '12'
        Color               = 'White'
        BackgroundColor     = 'ForestGreen' 
        HorizontalAlignment = 'Center'
        WrapText            = $True
    }
    $Worksheet | Format-Cell @HeadParams
    $Worksheet | Set-FreezePane -Row 2
    $Excel | Close-Excel -Save

**Comment by RamblingCookieMonster** [comment]
Hi!

I wanted to argue with this one, but looking around at existing Cmdlets, it seems like a standard convention to write an error if a specific query (not a general query that could return multiple results) does not return an item.

Will look at setting this up and the downstream effects it might have.

Thanks!

**Comment by DarkLite1** [comment]
The thing is that I changed the name of my worksheet earlier on in the code. But later on I wanted to do some formatting on it and used 'Get-Worksheet -Name OldName'. My formatting wasn't done and I thought I missed something. In cases like this, it should just throw an error saying 'I can't find what you're asking me'. It would have made the troubleshooting a lot easier :P
