### ISSUE TITLE
ParamterSet in Export-XLXS.ps1 cannot be resolved with non-Pivot and OfficeOpenXml.ExcelPackage object

### ISSUE THREAD

**Issue by jaols** [RamblingCookieMonster/PSExcel#14]
The following code does not work:

$xlDoc = New-Excel
Export-XLSX -Excel $xlDoc -InputObject $ppMembers -Table

Workaround:
Change to [CmdletBinding(DefaultParameterSetName='Excel-NoPivot')]
OR
Change the paramterset for table switch:
        [parameter( ParameterSetName = 'Excel-NoPivot')]
        [parameter( ParameterSetName = 'Path-NoPivot')]
        [switch]$Table,
OR
Add a parameter switch for non-pivot:
        [parameter( ParameterSetName = 'Excel-NoPivot')]
        [parameter( ParameterSetName = 'Path-NoPivot')]
        [switch]$NoPivot,

**Comment by RamblingCookieMonster** [comment]
Hi!

So, might need some input on this:

* Changing default parameter set leads to the same behavior with Path input
* Changing Table parameterset removes it as an option if a pivot is specified. Also, table isn't the only parameter affected
* Adding NoPivot seems painful

Alternatives that seem acceptable, but, still not optimal:

* Remove ExcelPackage input. Only accept Path input. Removes parameterset confusion, simplifies function. Reduces flexibility.
* Remove Pivot/NoPivot parametersets. Used these to limit visibility of parameters, but, they're a bit of a pain. All functionality remains intact. User experience suffers slightly.

What do you think? My choice would be the last one (only parametersets would be Excel, Path).

Cheers!
