### ISSUE TITLE
Why not let Export-XLSX.ps1 return the $Excel-object?

### ISSUE THREAD

**Issue by jaols** [RamblingCookieMonster/PSExcel#15]
if($PSBoundParameters.ContainsKey('Path'))
            {
                $Excel.SaveAs($Path)                
            }
            #Return object
            $Excel                  
    }
}

This will make it possible to stream data into a mail attachment without writing to a tmp-file (which will be locked as long as PowerShell is running).

**Comment by RamblingCookieMonster** [comment]
Sure, rather than always returning it, we can add a 'Passthru' switch, if that would make sense.

Thanks!
