### ISSUE TITLE
Using OfficeOpenXml.ExcelPackage as input object will fail in Export-XLSX.ps1 due to re-creation of the object in code. 

### ISSUE THREAD

**Issue by jaols** [RamblingCookieMonster/PSExcel#16]
Solution:
     #initialize stuff
            $RowIndex = 2
            Try
            {
                if ($Excel -eq $Null) {
                    $Excel = New-Object OfficeOpenXml.ExcelPackage($Path) -ErrorAction Stop
                }

**Comment by RamblingCookieMonster** [comment]
Hi!

Thanks for pointing this out, apologies for the delay, fixed in c86c6bfad08379e006610566be2e43bd3e3ece45

Cheers!
