### ISSUE TITLE
Could not readout cell from excel sheet called "allData"

### ISSUE THREAD

**Issue by hg-smart** [RamblingCookieMonster/PSExcel#23]
Hi...

Does anyone know what i am doing wrong ?

$Excel = New-Excel -Path "C:\temp\Demo.xlsx"
$Workbook  = $Excel    | Get-Workbook
$Worksheet = $Workbook | Get-Worksheet -Name "allData"
$Worksheet | Get-CellValue -Coordinates  "B1:B1"

I simply want to readout cell value B1 in Excel Sheet called allData...

Best
Hansjörg

**Comment by RamblingCookieMonster** [comment]
Hi!  What does that end up doing, and what was your expected output? I ran a quick demo, seemed to work as expected:

Loaded up test data:
![image](https://cloud.githubusercontent.com/assets/6377597/11003748/75157468-8482-11e5-93a6-b17b261e40a8.png)

Ran the following code:

```powershell
$Excel = New-Excel -Path "C:\temp\Demo.xlsx"
$Workbook = $Excel | Get-Workbook
$Worksheet = $Workbook | Get-Worksheet -Name "allData"
$Worksheet | Get-CellValue -Coordinates "B1:B1"
```

![image](https://cloud.githubusercontent.com/assets/6377597/11003799/c475b27a-8482-11e5-943b-bcb673150ae8.png)

I could expand that value (Get-CellValue... | Select -ExpandProperty Interesting), or, if I don't know what that value is (Sounds like you might be in that situation), I could specify an alternate header:

![image](https://cloud.githubusercontent.com/assets/6377597/11003874/24564fa6-8483-11e5-9dbf-2a5891e1c390.png)

This gives me the expected value.

Let me know if you're still running into trouble; knowing what sort of data is in that cell might help troubleshoot if so.

Cheers!

**Comment by hg-smart** [comment]
Hi, 
thank you very much, unfortunately there is a huge time difference between NY and Switzerland... 

i ran the following code 

![get-cellvalue 01](https://cloud.githubusercontent.com/assets/3541596/11031549/96c71486-86d5-11e5-86a2-b68531ea6fb4.PNG)


What is strange for me that the last statement shows the value ... and the other returns 6 rows... (File has 6 Sheets) ???

**Comment by hg-smart** [comment]
![get-cellvalue 02](https://cloud.githubusercontent.com/assets/3541596/11031593/f3734c22-86d5-11e5-8329-6b0582c9e6c4.PNG)

this should be a better screenshot

**Comment by RamblingCookieMonster** [comment]
Hi again!

Any chance you could post or e-mail a sanitized spreadsheet that behaves like this? E-mail is FirstName.LastName@gmail.com, with my name from a picture on [this page](http://ramblingcookiemonster.github.io/about/)

Thanks!

Warren

**Comment by RamblingCookieMonster** [comment]
Hi again!

Closing this out for now to clean up outstanding issues - if you do have a sanitized spreadsheet that behaves like this, do consider posting it to help debug!

Cheers!
