### ISSUE TITLE
Add support for functions to PivotValues parameter in Export-XLSX

### ISSUE THREAD

**Issue by replicaJunction** [RamblingCookieMonster/PSExcel#26]
Hi!

I've needed to make a few PivotTables and associated graphs that need to use a summary function - for example, to count the number of occurrences of a single item.

The [ImportExcel module handles this](https://github.com/dfinke/ImportExcel/blob/master/Export-Excel.ps1#L283-L295) by accepting a variable-typed parameter for PivotData. It looks like to specify an alternate function, that module uses a hashtable instead of a String.

``` powershell
# Count occurrences of each process name
gps | Export-Excel @otherArguments -PivotData @{name='count'}
```

Since in this module, the PivotValues parameter in Add-PivotTable is defined as a String[], the same approach wouldn't work. Would a separate parameter be appropriate (something like PivotFunction)?

I'm happy to submit a pull request for this if you'd like; I'd just need to do it from home instead of on my work machine. :)

Thanks!
~replica

**Comment by replicaJunction** [comment]
Looks like the ExcelPivotTableDataField class uses an enum for its valid values - OfficeOpenXml.Table.PivotTable.DataFieldFunctions. For type safety, the new parameter could be of that type.

**Comment by replicaJunction** [comment]
I went ahead and submitted a PR with that change (adding a parameter). Sorry about the double commit and the typo - that'll teach me not to commit before I run Pester!

One thing I didn't think about - what if the user wants two sets of data in their pivot table, each with a different function?

The PivotFunction parameter could accept an array of Strings and apply them in the same order as values in the PivotValues parameter, but that seems a bit clumsy to me. Accepting a variable type for the PivotValues parameter also seems a bit awkward, since that allows the user to do something silly (like try to use a weirdly-typed object).

Anyway, I feel like this PR is at least a step forward. If you've got any thoughts on multiple functions and how to distinguish between them, I'd be glad to modify this code.

**Comment by RamblingCookieMonster** [comment]
Closing this out for now - if folks are interested in extending it, feel free to submit an issue or issue+pr!
