### ISSUE TITLE
Exporting object with embedded object

### ISSUE THREAD

**Issue by mdw2** [RamblingCookieMonster/PSExcel#28]
PSExcel is an amazing module! 

Do you have any recommendations on how to deal with objects with embedded objects?  For example, when doing the following command:
Get-ADUser username -Properties ProxyAddresses | Export-XLSX c:\test.xlsx

When opening Excel, under the ProxyAddresses column it says "Microsoft.ActiveDirectory.Management.ADPropertyValueCollection".  

I could programmatically test each object to see if there is a collection then build a new string array with the data, but I'm wondering if there is an easier way?  I was hoping there was an argument that would do the work for me, but couldn't find one :)

**Comment by RamblingCookieMonster** [comment]
Hello!

It sounds like you already know the answer, but just in case:

* [This post](https://learn-powershell.net/2014/01/24/avoiding-system-object-or-similar-output-when-using-export-csv/) by @proxb illustrates why you might be seeing those, and potential workarounds.

* You can find a specific example for ProxyAddresses [here](https://blogs.technet.microsoft.com/heyscriptingguy/2013/07/22/export-user-names-and-proxy-addresses-to-csv-file/)

Cheers!
