### ISSUE TITLE
Import-Module PSExcel -Force not importing .dll

### ISSUE THREAD

**Issue by nadvolod** [RamblingCookieMonster/PSExcel#31]
Hi, when I do Import-Module PSExcel -Force , it won't import the .dll. Here is the error I get.

Add-Type : Could not load file or assembly 
'file:///C:\Users\nadvolodkin\Documents\WindowsPowerShell\Modules\PSExcel\lib\epplus.dll' or one of its 
dependencies. Operation is not supported. (Exception from HRESULT: 0x80131515)

**Comment by RamblingCookieMonster** [comment]
Hi there!

Guessing it's related to the dll:

* It might need to be [unblocked](https://blogs.msdn.microsoft.com/delay/p/unblockingdownloadedfile/)
* If you have whitelisting software, it might be blocking the dll (seems less likely)

Cheers!
