### ISSUE TITLE
$VerbosePreference = 'SilentlyContinue' not working?

### ISSUE THREAD

**Issue by willemdh** [RamblingCookieMonster/PSExcel#46]
Whatever I try, I seem unable to suppress the Exporting verbose messages when importing the module.

    $VerbosePreference = 'SilentlyContinue'
    Import-Module PSExcel | Out-Null
    VERBOSE: Exporting function 'Add-PivotChart'.
    VERBOSE: Exporting function 'Add-PivotTable'.
    VERBOSE: Exporting function 'Add-Table'.
    VERBOSE: Exporting function 'Close-Excel'.
    VERBOSE: Exporting function 'ConvertTo-ExcelCoordinate'.
    VERBOSE: Exporting function 'Export-XLSX'.
    VERBOSE: Exporting function 'Format-Cell'.
    VERBOSE: Exporting function 'Get-CellValue'.
    VERBOSE: Exporting function 'Get-Workbook'.
    VERBOSE: Exporting function 'Get-Worksheet'.
    VERBOSE: Exporting function 'Import-XLSX'.
    VERBOSE: Exporting function 'Join-Object'.
    VERBOSE: Exporting function 'Join-Worksheet'.
    VERBOSE: Exporting function 'New-Excel'.
    VERBOSE: Exporting function 'Save-Excel'.
    VERBOSE: Exporting function 'Search-CellValue'.
    VERBOSE: Exporting function 'Set-CellValue'.
    VERBOSE: Exporting function 'Set-FreezePane'.

**Comment by RamblingCookieMonster** [comment]
Hiyo! Closing this out - if it's still happening feel free to open it back up - only initial thought would be a default parameter perhaps?
