### ISSUE TITLE
Join-Worksheet ignores specified parameter "DestinationWorksheetName"

### ISSUE THREAD

**Issue by robmatesick** [RamblingCookieMonster/PSExcel#58]
The function `Join-Worksheet` documents and accepts named parameter `DestinationWorksheetName`.  However, it does not actually pass that to the `Export-XLSX` function.  

The fix is to pass this parameter value as argument `WorksheetName` to the `Export-XLSX` function.

**Comment by RamblingCookieMonster** [comment]
Eek!  Good catch, thanks for the note!  Feel free to submit a pull request, otherwise might be a little while before I remember to get back to it

Cheers!
