### ISSUE TITLE
Detecting Macros

### ISSUE THREAD

**Issue by dimmyr** [RamblingCookieMonster/PSExcel#60]
Could this be used to detect macro content in files (or especially extract the VPA code)?  I'm looking for a faster method than COM or the python-based OleTools.

**Comment by RamblingCookieMonster** [comment]
Hiyo!

Looks like [this is possible](https://stackoverflow.com/questions/39598677/get-all-the-vba-macros-of-a-workbook-by-epplus), assuming the version of EPPlus we include covers that functionality.

Try loading up your file, exploring the object:

```powershell
$Excel = New-Excel -Path "C:\Excel.xlsm"
$Excel.Workbook.VbaProject.Modules
```

Cheers!

**Comment by dimmyr** [comment]
That worked great, thank you! 
Question: is there a way to extract macros from MS Word or MS Access as well?

**Comment by RamblingCookieMonster** [comment]
Awesome to hear!

Not sure on Word or Access unfortunately - unless they have comparable open source libraries like EPPlus, chances are you would likely need to use COM (I suspect COM might have similar methods, but no idea)

Yeah - this is only for xlsx files - basically, anything EPPlus supports (we just wrap that library)

Cheers!
