### ISSUE TITLE
Export-XLSX -WorkSheetName "More Then 31 characters"

### ISSUE THREAD

**Issue by Agazoth** [RamblingCookieMonster/PSExcel#62]
When exporting data to a worksheet with a name longer then 31 characters you get this throw error:
At C:\Program Files\WindowsPowerShell\Modules\psexcel\1.0.2\Add-Table.ps1:151 char:13
+             Throw "Could not get worksheets to search: $_"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not get w...th (parenthes
:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not get worksheets to search: Yet another tab with (parenthesis) could not be foun
   d. Valid worksheets:

Can be mitigated by adding
[ValidateLength(1,31)]
in line 206

**Comment by RamblingCookieMonster** [comment]
Good find!  Feel free to submit a pull request, otherwise, will try to grab this over the weekend - cheers!
