### ISSUE TITLE
AutoFit errors out when run run within an Inline function

### ISSUE THREAD

**Issue by kduraira** [RamblingCookieMonster/PSExcel#64]
Hi,

I get the following error when I run PS workflow as an InlineScript within Azure Automation runbook. It works fine when run as a PS file: The usage is: $vmScheduleObject | select 'VM Name', 'ResourceGroup Name', 'Shutdown Schedule', 'Schedule Expires' | Export-XLSX -Path $blob -Table -AutoFit -Force

Exception calling "AutoFitColumns" with "0" argument(s): "A generic error occurred in GDI+."
At Get-VMOnDemandSchedule:3 char:3
+ 
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : ExternalException

Any advise on this would be great.

**Comment by RamblingCookieMonster** [comment]
Hiyo!

It looks like [you aren't the only one](https://stackoverflow.com/questions/26905314/epplus-running-in-azure-produces-a-generic-error-occurred-in-gdi); unfortunately, it doesn't appear that there's an answer.  This is on the EPPlus library side, unfortunately that's a bit outside my expertise

Going to close this out - if you ever find the answer and remember this thread, feel free to reply with details - cheers!

Good luck!
